### ISSUE TITLE
可以使用别的软件代替Anaconda么？

### ISSUE THREAD

**Issue by HelloFanzai** [emma-oc/ds-class-intro#28]
我们以后的课程必须用Anaconda python呢？还是其他软件如果可以运行python和jupyter notebook就可以呢？

**Comment by emma-oc** [comment]
Anaconda只是帮助管理environment和package的，python是独立于它的，不装Anaconda也可以直接运行python。jupyter notebook是包含在Anaconda里的一个工具，帮你set up一个interactive的环境可以实时看到运行结果。
我们上课用jupyter notebook主要因为比较好上手且可以写markdown把上课的内容放进去，如果你习惯用terminal或者IDE可以随意用，第二次作业开始我会要求大家交`.py`格式的作业~
