### ISSUE TITLE
非默认path 用命令行不能打开jupyter notebook

### ISSUE THREAD

**Issue by HelloFanzai** [emma-oc/ds-class-intro#35]
win10用户，在非默认path 用命令行打开jupyter notebook的话会提示
'jupyter' is not recognized as an internal or external command,
operable program or batch file.

system path已经添加了

**Comment by emma-oc** [comment]
试试这个post第一个答案：https://stackoverflow.com/questions/35134225/jupyter-from-cmd-line-in-windows
`where jupyter`

这个看起来也靠谱：https://stackoverflow.com/questions/41034866/running-jupyter-via-command-line-on-windows/43239824#43239824
