### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Cruise-Ling** [emma-oc/ds-class-intro#7]
clone到本地之后，我的本地只有class 01，没有class 02.

**Comment by Cruise-Ling** [comment]
而且我folk到我的github里面，我好像看不到issues这一栏

**Comment by emma-oc** [comment]
> clone到本地之后，我的本地只有class 01，没有class 02.

I'm suspecting your fork is not synced with my original repo (upstream). Follow bullet point 3 in [https://github.com/emma-oc/ds-class-intro/blob/class02/class01/git_setup.md#task-for-the-class](https://github.com/emma-oc/ds-class-intro/blob/class02/class01/git_setup.md#task-for-the-class) to set up your upstream and sync. After that, you should see `upstream/class02'. You can then do `git branch class02 upstream/class02` and then can `git checkout class02`.

**Comment by emma-oc** [comment]
> 而且我folk到我的github里面，我好像看不到issues这一栏

Check this answer: https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig

**Comment by emma-oc** [comment]
I have updated the instructions, closing this issue.
